config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  resources :cars do
    collection do
      post :import
      get :search
      get :models
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
# == Schema Information
#
# Table name: cars
#
#  id                :bigint           not null, primary key
#  brand             :string
#  model             :string
#  price             :decimal(, )
#  production_year   :integer
#  cylinder_capacity :decimal(, )
#  mileage           :decimal(, )
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#
class Car < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  require "csv"
  before_action :set_file, only: [:import]
  
  def index
    @cars = Car.all
  end

  def import
    # Controller validation to csv file extention
    return redirect_to cars_path, notice: "csv file only, please!" unless @file&.content_type == "text/csv"
    # Call to import cars service
    success, message = CsvImportCarsService.new.call(@file)
    # Response
    if success
      redirect_to cars_path, notice: "Data has been imported successfully."
    else
      redirect_to cars_path, notice: "Import cars error.", status: :unprocessable_entity
    end
  end

  def search
    @data = {}
    request = Car.where(brand: params[:brand])
                .where(model: params[:model])
                .select("production_year, avg(price) as price")
                .group("production_year")

    request.each {|r| @data.store(r.production_year, r.price) }
    # debugger
    respond_to do |format|
      format.html
      format.turbo_stream
    end
  end

  def models
    @models = Car.where(brand: params[:model]).group(:model).count.map { |key, value| [key, key] }
    @target = params[:target]
    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_file
    @file = params[:file]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/index.html.erb
<div class="container">
  <div class="mt-2 import-form">
    <h2>Import car data</h2>
    <%= form_with url: import_cars_path, method: :post, class: "form-control shadow-sm" do |f| %>
      <%= f.file_field :file, class: "form-control", accept: ".csv" %>
      <%= f.button "Import", class: "btn btn-primary mt-2" %>
    <% end %>
    We have <strong><%= @cars.count %></strong> records in database.
  </div>
</div>

app/views/cars/models.turbo_stream.erb
<%# Updates model select with @models from controller %>
<%= turbo_stream.update @target do %>
  <%= options_for_select @models %>
<% end %>

app/views/cars/search.html.erb
<div class="container">
  <h2>Search car data</h2>
  <%# Seach form %>
  <div class="d-flex justify-content-center border rounded py-4 shadow-sm" data-controller="car-model" data-car-model-url-value="<%= models_cars_path %>" data-car-model-param-value="model">
    <%= form_with( url: search_cars_path, method: :get, data: { turbo_stream: true, turbo_frame: 'charts'}, class: "d-block d-md-flex flex-row flex-wrap gap-2 justify-content-end align-items-center" ) do |form| %>
      
      <div class="col-auto mb-2">
        <%= form.select :brand, Car.group(:brand).count.map { |key, value| [key, key] }.sort, { prompt: "Brand" }, { class: 'form-select', data: { action: "change->car-model#change" } } %>
      </div>

      <div class="col-auto mb-2">
        <%= form.select :model, [], { prompt: "Model" }, { class: 'form-select', data: { car_model_target: "modelSelect" } } %>
      </div>

      <div class="col-auto mb-2">
        <%= form.submit "Search", class: "btn btn-primary" %>
      </div>
    <% end %>
  </div>

  <%= turbo_frame_tag "charts" %>
</div>

app/views/cars/search.turbo_stream.erb
<%= turbo_stream.update "charts" do %>
  <% unless @data.nil? %>
    <div data-controller="line-chart" data-line-chart-labels-value="<%= @data.keys %>" data-line-chart-values-value="<%= @data.values %>">
      <canvas id="chart" data-line-chart-target="chart"></canvas>
    </div>
  <% end %>
<% end %>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, message| %>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <%= message %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataCars</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <div id="flash" class="flash">
      <%= render 'layouts/flash' %>
    </div>

    <%= yield %>
  </body>
</html>